<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\EmailProvider;

class EmailProviderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $providers = [
            [
                'name' => 'gmail',
                'display_name' => 'Gmail',
                'type' => 'gmail_api',
                'icon' => 'gmail.png',
                'color' => '#EA4335',
                'imap_host' => 'imap.gmail.com',
                'imap_port' => 993,
                'imap_encryption' => 'ssl',
                'smtp_host' => 'smtp.gmail.com',
                'smtp_port' => 587,
                'smtp_encryption' => 'tls',
                'smtp_auth_required' => true,
                'api_endpoint' => 'https://gmail.googleapis.com',
                'api_version' => 'v1',
                'oauth_client_id' => config('services.google.client_id'),
                'oauth_client_secret' => config('services.google.client_secret'),
                'oauth_redirect_uri' => config('app.url') . '/auth/google/callback',
                'oauth_scopes' => [
                    'https://www.googleapis.com/auth/gmail.readonly',
                    'https://www.googleapis.com/auth/gmail.send',
                    'https://www.googleapis.com/auth/gmail.modify'
                ],
                'timeout' => 30,
                'verify_ssl' => true,
                'auth_type' => 'oauth',
                'is_active' => true,
                'description' => 'Google Gmail with OAuth2 authentication',
                'setup_instructions' => 'To use Gmail, you need to enable 2-factor authentication and create an App Password, or use OAuth2 authentication.',
            ],
            [
                'name' => 'microsoft',
                'display_name' => 'Microsoft 365 / Outlook',
                'type' => 'microsoft_graph',
                'icon' => 'microsoft.png',
                'color' => '#0078D4',
                'imap_host' => 'outlook.office365.com',
                'imap_port' => 993,
                'imap_encryption' => 'ssl',
                'smtp_host' => 'smtp.office365.com',
                'smtp_port' => 587,
                'smtp_encryption' => 'tls',
                'smtp_auth_required' => true,
                'api_endpoint' => 'https://graph.microsoft.com',
                'api_version' => 'v1.0',
                'oauth_client_id' => config('services.microsoft.client_id'),
                'oauth_client_secret' => config('services.microsoft.client_secret'),
                'oauth_redirect_uri' => config('app.url') . '/auth/microsoft/callback',
                'oauth_scopes' => [
                    'https://graph.microsoft.com/Mail.Read',
                    'https://graph.microsoft.com/Mail.Send',
                    'https://graph.microsoft.com/Mail.ReadWrite'
                ],
                'timeout' => 30,
                'verify_ssl' => true,
                'auth_type' => 'oauth',
                'is_active' => true,
                'description' => 'Microsoft 365 and Outlook.com with Microsoft Graph API',
                'setup_instructions' => 'To use Microsoft 365, you need to register an application in Azure AD and configure the necessary permissions.',
            ],
            [
                'name' => 'ovh',
                'display_name' => 'OVH',
                'type' => 'imap',
                'icon' => 'ovh.png',
                'color' => '#123F6D',
                'imap_host' => 'ssl0.ovh.net',
                'imap_port' => 993,
                'imap_encryption' => 'ssl',
                'pop3_host' => 'ssl0.ovh.net',
                'pop3_port' => 995,
                'pop3_encryption' => 'ssl',
                'smtp_host' => 'ssl0.ovh.net',
                'smtp_port' => 587,
                'smtp_encryption' => 'tls',
                'smtp_auth_required' => true,
                'timeout' => 30,
                'verify_ssl' => true,
                'auth_type' => 'password',
                'is_active' => true,
                'description' => 'OVH email hosting with IMAP/POP3/SMTP support',
                'setup_instructions' => 'Use your OVH email address and password. Make sure IMAP is enabled in your OVH control panel.',
            ],
            [
                'name' => 'aruba',
                'display_name' => 'Aruba',
                'type' => 'imap',
                'icon' => 'aruba.png',
                'color' => '#00A3E0',
                'imap_host' => 'imap.aruba.it',
                'imap_port' => 993,
                'imap_encryption' => 'ssl',
                'pop3_host' => 'pop3.aruba.it',
                'pop3_port' => 995,
                'pop3_encryption' => 'ssl',
                'smtp_host' => 'smtp.aruba.it',
                'smtp_port' => 587,
                'smtp_encryption' => 'tls',
                'smtp_auth_required' => true,
                'timeout' => 30,
                'verify_ssl' => true,
                'auth_type' => 'password',
                'is_active' => true,
                'description' => 'Aruba email hosting with IMAP/POP3/SMTP support',
                'setup_instructions' => 'Use your Aruba email address and password. Make sure IMAP is enabled in your Aruba control panel.',
            ],
            [
                'name' => 'libero',
                'display_name' => 'Libero',
                'type' => 'imap',
                'icon' => 'libero.png',
                'color' => '#FF6B35',
                'imap_host' => 'imap.libero.it',
                'imap_port' => 993,
                'imap_encryption' => 'ssl',
                'pop3_host' => 'pop3.libero.it',
                'pop3_port' => 995,
                'pop3_encryption' => 'ssl',
                'smtp_host' => 'smtp.libero.it',
                'smtp_port' => 587,
                'smtp_encryption' => 'tls',
                'smtp_auth_required' => true,
                'timeout' => 30,
                'verify_ssl' => true,
                'auth_type' => 'password',
                'is_active' => true,
                'description' => 'Libero email with IMAP/POP3/SMTP support',
                'setup_instructions' => 'Use your Libero email address and password. You may need to enable "Less secure app access" or use an App Password.',
            ],
            [
                'name' => 'yahoo',
                'display_name' => 'Yahoo Mail',
                'type' => 'imap',
                'icon' => 'yahoo.png',
                'color' => '#720E9E',
                'imap_host' => 'imap.mail.yahoo.com',
                'imap_port' => 993,
                'imap_encryption' => 'ssl',
                'pop3_host' => 'pop.mail.yahoo.com',
                'pop3_port' => 995,
                'pop3_encryption' => 'ssl',
                'smtp_host' => 'smtp.mail.yahoo.com',
                'smtp_port' => 587,
                'smtp_encryption' => 'tls',
                'smtp_auth_required' => true,
                'timeout' => 30,
                'verify_ssl' => true,
                'auth_type' => 'password',
                'is_active' => true,
                'description' => 'Yahoo Mail with IMAP/POP3/SMTP support',
                'setup_instructions' => 'You need to generate an App Password in your Yahoo account settings. Regular password won\'t work.',
            ],
            [
                'name' => 'custom',
                'display_name' => 'Custom IMAP',
                'type' => 'imap',
                'icon' => 'custom.png',
                'color' => '#6B7280',
                'timeout' => 30,
                'verify_ssl' => true,
                'auth_type' => 'password',
                'is_active' => true,
                'description' => 'Custom IMAP server configuration',
                'setup_instructions' => 'Enter your custom IMAP server details. You can configure host, port, and encryption settings.',
            ],
        ];

        foreach ($providers as $provider) {
            EmailProvider::updateOrCreate(
                ['name' => $provider['name']],
                $provider
            );
        }
    }
}
